apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: spry-spanner-345015
  artifacts:
    - image: li123812i38/ticketing-auth
    # - image: gcr.io/spry-spanner-345015/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: li123812i38/ticketing-client
    # - image: gcr.io/spry-spanner-345015/ticketing-auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
